
          const g = ac.createGain();
          o.type = type;
          o.frequency.value = freq;
          if (detune) o.detune.value = detune;
          g.gain.value = gain;
          o.connect(g);
          g.connect(dest);
          o.start();
          nodes.push(o, g);
          return o;
        };
        mkOsc("sine", 55, 0.22, 0);
        mkOsc("sine", 55.4, 0.12, 6);
        mkOsc("triangle", 82.4, 0.08, -4);
        mkOsc("sine", 110, 0.05, 3);
        const n = ac.sampleRate * 4;
        const buf = ac.createBuffer(1, n, ac.sampleRate);
        const data = buf.getChannelData(0);
        for (let i = 0; i < n; i++) data[i] = Math.random() * 2 - 1;
        const src = ac.createBufferSource();
        src.buffer = buf;
        src.loop = true;
        const bp = ac.createBiquadFilter();
        bp.type = "bandpass";
        bp.frequency.value = 420;
        bp.Q.value = 2.2;
        const ng = ac.createGain();
        ng.gain.value = 0.045;
        const lfo = ac.createOscillator();
        const lfoG = ac.createGain();
        lfo.frequency.value = 0.07;
        lfoG.gain.value = 180;
        lfo.connect(lfoG);
        lfoG.connect(bp.frequency);
        src.connect(bp);
        bp.connect(ng);
        ng.connect(dest);
        src.start();
        lfo.start();
        nodes.push(src, bp, ng, lfo, lfoG);
        const motif = [220, 261.63, 293.66, 329.63, 392, 329.63, 293.66, 261.63];
        let mi = 0;
        const playMotif = () => {
          if (!this.musicNodes || this.muted) return;
          const f = motif[mi % motif.length];
          mi += 1;
          const o = ac.createOscillator();
          const g = ac.createGain();
          const lp = ac.createBiquadFilter();
          o.type = "sine";
          o.frequency.value = f;
          lp.type = "lowpass";
          lp.frequency.value = 1400;
          const now = ac.currentTime;
          g.gain.setValueAtTime(0.0001, now);
          g.gain.exponentialRampToValueAtTime(0.04, now + 0.05);
          g.gain.exponentialRampToValueAtTime(0.0001, now + 1.2);
          o.connect(lp);
          lp.connect(g);
          g.connect(dest);
          o.start(now);
          o.stop(now + 1.3);
        };
        this.motifTimer = setInterval(playMotif, 2800);
        playMotif();
        this.musicNodes = nodes;
      }
      this.musicGain.gain.cancelScheduledValues(t0);
      this.musicGain.gain.setValueAtTime(Math.max(0.0001, this.musicGain.gain.value), t0);